#!/usr/bin/env python3
"""One-time fixture authoring, outside the runtime build; no downloaded media.

Pass the fixture-only FFmpeg executable and a NEW output directory. Gate 1 uses
the checked-in, hash-locked outputs and never links or installs these encoders.
"""
import hashlib
import json
from pathlib import Path
import struct
import subprocess
import sys
import tempfile


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main():
    encoder = Path(sys.argv[1]).resolve()
    output = Path(sys.argv[2]).resolve()
    output.mkdir()
    commands = []
    with tempfile.TemporaryDirectory() as directory:
        temp = Path(directory)
        # Integer-only moving luma/chroma patterns: 24 frames, 128x72 YUV420P.
        video = b''.join(bytes((16 + (x * 2 + y + frame * 7) % 220
                                for y in range(72) for x in range(128))) +
                         bytes([96 + frame]) * (64 * 36) +
                         bytes([160 - frame]) * (64 * 36) for frame in range(24))
        # Integer triangle wave, exactly 48,000 signed 16-bit mono samples.
        audio = b''.join(struct.pack('<h', ((i % 200) if i % 200 < 100
                                          else 200 - i % 200) * 400 - 20000)
                         for i in range(48000))
        (temp / 'pattern.yuv').write_bytes(video)
        (temp / 'wave.pcm').write_bytes(audio)
        common = ['-hide_banner', '-nostdin', '-y', '-v', 'error', '-fflags', '+bitexact']
        vin = ['-f', 'rawvideo', '-pixel_format', 'yuv420p', '-video_size', '128x72',
               '-framerate', '24', '-i', 'pattern.yuv', '-frames:v', '24', '-an']
        ain = ['-f', 's16le', '-ar', '48000', '-ac', '1', '-i', 'wave.pcm', '-vn']
        recipes = {
            'av1.mp4': vin + ['-c:v', 'libsvtav1', '-preset', '12', '-crf', '32',
                              '-svtav1-params', 'lp=1', '-threads', '1'],
            'vp9.webm': vin + ['-c:v', 'libvpx-vp9', '-lossless', '1', '-threads', '1',
                               '-row-mt', '0', '-map_metadata', '-1'],
            'mp3.mp3': ain + ['-c:a', 'libmp3lame', '-b:a', '128k', '-threads', '1'],
            'alac.m4a': ain + ['-c:a', 'alac', '-threads', '1'],
        }
        for name, args in recipes.items():
            argv = common + args + ['-flags', '+bitexact', '-fflags', '+bitexact', str(output / name)]
            result = subprocess.run([str(encoder)] + argv, cwd=temp, capture_output=True, text=True)
            if result.returncode:
                raise RuntimeError(result.stderr)
            commands.append({'file': name, 'argv': ['FFMPEG'] + common + args +
                             ['-flags', '+bitexact', '-fflags', '+bitexact', name], 'encoder_log': result.stderr})
        manifest = {
            'origin': 'Original integer synthetic patterns generated by this repository; no third-party media.',
            'generator': 'scripts/generate_compat_fixtures.py',
            'fixture_only_ffmpeg': {'version': subprocess.check_output([str(encoder), '-version'], text=True),
                                    'sha256': sha(encoder)},
            'raw_sources': {'pattern.yuv': hashlib.sha256(video).hexdigest(),
                            'wave.pcm': hashlib.sha256(audio).hexdigest()},
            'commands': commands,
            'files': {p.name: {'sha256': sha(p), 'size_bytes': p.stat().st_size}
                      for p in sorted(output.iterdir())},
            'video': {'width': 128, 'height': 72, 'frames': 24, 'pixel_format': 'yuv420p'},
            'audio': {'sample_rate': 48000, 'channels': 1, 'samples': 48000},
        }
        (output / 'manifest.json').write_text(json.dumps(manifest, indent=2) + '\n')


if __name__ == '__main__':
    main()
